name: test-actions

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - run: echo "Hello World2"

      - uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.124.1'

      - name: Build
        run: hugo --minify

      - name: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public
  deploy:
    needs: build
